<?php
/**
 * @author Drajat Hasan
 * @email drajathasan20@gmail.com
 * @create date 2021-10-27 17:12:17
 * @modify date 2026-08-03 20:32:21
 * @desc This page modifies a PHP configuration file. Keep both its destination and
 *       generated content under this module's control; never derive either from a
 *       request value or from a writable template.
 */
// key to authenticate
define('INDEX_AUTH', '1');

// main system configuration
require '../../../sysconfig.inc.php';
// IP based access limitation
require LIB.'ip_based_access.inc.php';
do_checkIP('smc');
do_checkIP('smc-system');

// start the session
require SB.'admin/default/session.inc.php';
require SB.'admin/default/session_check.inc.php';
require SIMBIO.'simbio_GUI/form_maker/simbio_form_table_AJAX.inc.php';
require SIMBIO.'simbio_GUI/table/simbio_table.inc.php';
require SIMBIO.'simbio_DB/simbio_dbop.inc.php';

$configDirectory = realpath(SB . 'config');
$envConfigFile = $configDirectory ? $configDirectory . DS . 'env.php' : false;

function envsettingCurrentIp()
{
    return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '';
}

function envsettingEnvironment($value)
{
    return $value === 'production' ? 'production' : 'development';
}

function envsettingStoredDefaultEnvironment($file, $fallback)
{
    if (!$file || !is_file($file) || is_link($file) || !is_readable($file)) {
        return $fallback;
    }

    $contents = file_get_contents($file);
    if (!is_string($contents)) {
        return $fallback;
    }

    if (preg_match('/^\\s*\\$env\\s*=\\s*[\'\\"](production|development)[\'\\"]\\s*;/m', $contents, $matches)) {
        return $matches[1];
    }

    return $fallback;
}

function envsettingIpRange($value)
{
    if (!is_string($value) || trim($value) === '') {
        return array();
    }

    $range = array();
    foreach (explode(';', $value) as $ip) {
        $ip = trim($ip);
        if ($ip === '') {
            continue;
        }

        if (filter_var($ip, FILTER_VALIDATE_IP) === false) {
            return false;
        }

        $range[$ip] = $ip;
    }

    return array_values($range);
}

function envsettingFileContents($environment, $conditionalEnvironment, $basedOnIp, array $rangeIp)
{
    $environment = var_export($environment, true);
    $conditionalEnvironment = var_export($conditionalEnvironment, true);
    $basedOnIp = $basedOnIp ? 'true' : 'false';
    $rangeIp = var_export($rangeIp, true);

    return <<<PHP
<?php
/**
 * This file is generated by the System Environment Settings page.
 * Do not edit it through untrusted input.
 */
\$env = {$environment};
\$conditional_environment = {$conditionalEnvironment};
\$based_on_ip = {$basedOnIp};
\$range_ip = {$rangeIp};

if (\$based_on_ip) {
    // Only use the peer address. HTTP_X_FORWARDED_FOR is client-controlled
    // unless the deployment has an explicit trusted-proxy policy.
    if (in_array(\$_SERVER['REMOTE_ADDR'] ?? '', \$range_ip, true)) {
        \$env = \$conditional_environment;
    }
}

if (php_sapi_name() === 'cli') {
    \$env = \$conditional_environment !== \$env ? \$conditional_environment : \$env;
}
PHP;
}

function envsettingWriteFile($file, $contents)
{
    $directory = dirname($file);
    if (!is_dir($directory) || !is_writable($directory) || is_link($file)) {
        return false;
    }

    $temporaryFile = tempnam($directory, '.env-');
    if ($temporaryFile === false) {
        return false;
    }

    $written = file_put_contents($temporaryFile, $contents, LOCK_EX);
    if ($written === false || $written !== strlen($contents)) {
        @unlink($temporaryFile);
        return false;
    }

    @chmod($temporaryFile, 0640);
    if (!@rename($temporaryFile, $file)) {
        @unlink($temporaryFile);
        return false;
    }

    if (function_exists('opcache_invalidate')) {
        @opcache_invalidate($file, true);
    }

    return true;
}

if (!isset($_SESSION['uid']) || (int) $_SESSION['uid'] !== 1) {
    die('<div class="errorBox">' . __('You don\'t have enough privileges to edit this section') . '</div>');
}

// Do not let a malformed legacy configuration affect the form or generated file.
$env = envsettingEnvironment(isset($env) ? $env : 'development');
$conditional_environment = envsettingEnvironment(isset($conditional_environment) ? $conditional_environment : 'development');
$based_on_ip = !empty($based_on_ip);
$range_ip = isset($range_ip) && is_array($range_ip)
    ? array_values(array_filter($range_ip, function ($ip) {
        return is_string($ip) && filter_var($ip, FILTER_VALIDATE_IP) !== false;
    }))
    : array();

if (isset($_POST['saveData'])) {
    if (!simbio_form_maker::isTokenValid()) {
        toastr(__('Invalid form submission token!'))->error();
    } elseif ($configDirectory === false || dirname($envConfigFile) !== $configDirectory) {
        toastr(__('Configuration directory is not available.'))->error();
    } else {
        $inputEnvironment = isset($_POST['env']) && (string) $_POST['env'] === '1' ? 'production' : 'development';
        $basedOnIp = isset($_POST['basedIp']) && (string) $_POST['basedIp'] === '1';
        $inputRangeIp = envsettingIpRange(isset($_POST['rangeIp']) ? $_POST['rangeIp'] : '');

        if ($inputRangeIp === false) {
            toastr(__('Range IP must contain only valid IP addresses.'))->error();
        } else {
            // When IP mode is enabled, the selected environment applies only to
            // the approved addresses. The current default environment is kept.
            $environment = $basedOnIp
                ? envsettingStoredDefaultEnvironment($envConfigFile, $env)
                : $inputEnvironment;
            $contents = envsettingFileContents($environment, $inputEnvironment, $basedOnIp, $inputRangeIp);

            if (!envsettingWriteFile($envConfigFile, $contents)) {
                toastr(__('Unable to save configuration.'))->error();
            } else {
                utility::jsToastr(__('Success'), __('Configuration has been saved!'), 'success');
                redirect()->simbioAJAX(timeout: 0, url: $_SERVER['PHP_SELF']);
                exit;
            }
        }
    }
}

?>

<div class="menuBox">
  <div class="menuBoxInner systemIcon">
    <div class="per_title">
      <h2><?php echo __('System Environment Settings'); ?></h2>
    </div>
    <div class="infoBox">
      <?php echo __('SLiMS Environment preferences.'); ?>
    </div>
  </div>
</div>

<?php

// create new instance
$form = new simbio_form_table_AJAX('mainForm', $_SERVER['PHP_SELF'], 'post');

// Save setting button
$form->submit_button_attr = 'name="saveData" value="'.__('Save Settings').'" class="btn btn-default"';

// form table attributes
$form->table_attr = 'id="dataList" class="s-table table"';
$form->table_header_attr = 'class="alterCell font-weight-bold"';
$form->table_content_attr = 'class="alterCell2"';

// Your Environment
if ($based_on_ip)
{
    $thisEnv = ucfirst((!in_array(envsettingCurrentIp(), $range_ip, true) ? $env : $conditional_environment));
    $HTML = '<b>' . __($thisEnv) . '</b>';
    $form->addAnything('Your Environment Mode', $HTML);

    $env = $conditional_environment;
}

// Environment List
$EnvOptions = [
    [1, __('Production')],
    [0, __('Development')]
  ];
$label = __('System Environment Mode');
$form->addSelectList('env', $label, $EnvOptions, ( $env == 'production' ? 1 : 0 ) ,'class="form-control col-3"');
$BasedIpOptions = [
    [0, __('Disable')],
    [1, __('Enable')]
];
$form->addSelectList('basedIp', __('Environment for some IP?'), $BasedIpOptions, ( $based_on_ip ? 1 : 0 ) ,'class="form-control col-3"');
$form->addTextField('textarea', 'rangeIp', __('Range Ip wil be impacted with Environment. Example : 10.120.33.40;20.100.34.10. '), implode(';', $range_ip), 'style="margin-top: 0px; margin-bottom: 0px; height: 149px;" class="form-control" placeholder="'.__('Leave it empty, if you want to set environment to impact for all IP').'"');
// print out the object
echo $form->printOut();

echo '<script>
$(\'#mainForm\').submit(function() {
  window.toastr.info(\'' . __('Please wait') . '\', \'Info\')
});
</script>';
